"""fix mistake with Post model

Revision ID: b476161735a7
Revises: 64b70c3c2322
Create Date: 2023-10-19 03:07:48.382637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b476161735a7'
down_revision = '64b70c3c2322'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
