"""fix mistake with Like  model

Revision ID: ccaf9b520446
Revises: b476161735a7
Create Date: 2023-10-19 03:09:18.100981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccaf9b520446'
down_revision = 'b476161735a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
